name: Check PR to master

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  check_linting:
    name: Check linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Run clang-format
        uses: jidicula/clang-format-action@v4.13.0
        with:
          clang-format-version: '18'

  run_tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Install gtest
        uses: Bacondish2023/setup-googletest@v1

      - name: Create build directory
        run: mkdir build

      - name: Build
        run: cd build && cmake .. && make

      - name: Run tests
        run: build/gmpwrap_test
